; AMBIENTE 1: O CÓDIGO OFICIAL (PRODUÇÃO)
[env:producao]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
lib_deps =
  knolleary/PubSubClient @ ^2.8
; Avisa o compilador para ler SÓ o main.cpp e ignorar os outros
build_src_filter = +<main.cpp> 

; AMBIENTE 2: O CÓDIGO DE CALIBRAÇÃO
[env:calibracao]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
; Avisa o compilador para ler SÓ o calibracao.cpp e ignorar os outros
build_src_filter = +<calibracao.cpp>